{% set name = "spatialdata-plot" %}
{% set version = "0.2.11" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatialdata_plot-{{ version }}.tar.gz
  sha256: f6fb2b0552f9fb8c0ad9c6670581be9398de00496d73c3e57382a9c0fda2f645

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - matplotlib-base
    - matplotlib-scalebar
    - python >={{ python_min }}
    - scanpy
    - scikit-learn
    - spatialdata >=0.3.0

test:
  imports:
    - spatialdata_plot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/spatialdata-plot.git
  summary: Static plotting for spatial data.
  dev_url: https://github.com/scverse/spatialdata-plot.git
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LucaMarconato
    - giovp
    - timtreis
    - melonora
    - Sonja-Stockhaus
    - kevinyamauchi
